[platformio]
default_envs = teensy40

[env:teensy40]
platform = teensy
board = teensy40
framework = arduino

monitor_speed = 115200

lib_deps =
    pololu/Motoron @ ^1.5.0
    paulstoffregen/Encoder @ ^1.4.4
    pololu/LSM6 @ ^2.0.1

build_flags =
    -O2
    -DTEENSY_OPT_FAST
    -I include
    -DMAZE_WIDTH=16
    -DMAZE_HEIGHT=16

[env:teensy40-debug-3x3]
extends = env:teensy40
build_flags =
    ${env:teensy40.build_flags}
    -DDEBUG_MANUAL_MAZE_BUILD_MODE
    -DMAZE_WIDTH=3
    -DMAZE_HEIGHT=3

[env:teensy40-3x3]
extends = env:teensy40
build_flags =
    ${env:teensy40.build_flags}
    -DMAZE_WIDTH=3
    -DMAZE_HEIGHT=3
