[platformio]
default_envs = teensy31

[env:teensy31]
platform = teensy
board = teensy31
framework = arduino

monitor_speed = 115200

lib_deps =
    pololu/Motoron @ ^1.5.0
    paulstoffregen/Encoder @ ^1.4.4
    pololu/LSM6 @ ^2.0.1

build_flags =
    -O2
    -DTEENSY_OPT_FAST
    -I include

[env:teensy40]
platform = teensy
board = teensy40
framework = arduino

monitor_speed = 115200

lib_deps =
    pololu/Motoron @ ^1.5.0
    paulstoffregen/Encoder @ ^1.4.4
    pololu/LSM6 @ ^2.0.1

build_flags =
    -O2
    -DTEENSY_OPT_FAST
    -I include

